# Site settings
title: Andy Gillette
email: andy.gillette@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my website. It's a good website. Not great, sure, but good. I blogs here and wrote an about page.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://agillette.github.io" # the base hostname & protocol for your site
twitter_username: agillette
github_username:  agillette

# Build settings
markdown: kramdown

